services:
  postgres:
    image: postgres:17
    container_name: insurance-premium-db
    environment:
      POSTGRES_DB: insurance_premium
      POSTGRES_USER: insurance_user
      POSTGRES_PASSWORD: insurance_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
